## Plan
First use 1 hour resolution data, run a fourier transform and use a simple decision tree. <br>
Maybe even simple linear regression using only the n largest spikes in the fourier.

In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn import tree
from matplotlib import pyplot as plt

C:\Users\bfesc\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [2]:
data = pd.read_csv('C:\\Users\\bfesc\\Documents\\Master_thesis\\master_data\\dataport\\dataport-1hr-full.csv', 
                header = 0, index_col = 0)
data.index = data.index.map(lambda x: x[:-3])
data.index = pd.to_datetime(data.index)
data.head()

             dataid      grid
localminute
2017-01-01       26  1.788783
2017-01-01     9938  1.064767
2017-01-01       59  0.805333
2017-01-01     9647  1.081900
2017-01-01       93  0.916167

In [3]:
houses = pd.DataFrame(index = data[data['dataid'] == 26].index)
houses_fft = pd.DataFrame()

for i in np.unique(data['dataid']):
    if len(data[data['dataid'] == i]['grid']) == len(houses.index):
        houses[str(i)] = data[data['dataid'] == i]['grid']
        houses_fft[str(i)] = np.fft.fft(houses[str(i)])
    
houses.head()

,26,59,86,93,94,114,171,232,252,370,...,9776,9875,9932,9934,9935,9937,9938,9939,9971,9983
localminute,,,,,,,,,,,,,,,,,,,,,
2017-01-01 00:00:00,1.788783,0.805333,0.683733,0.916167,2.054933,0.552000,0.456217,0.569400,1.218867,0.862550,...,2.136917,0.894183,6.523617,0.670233,1.666183,0.274333,1.064767,1.158533,0.348083,1.946800
2017-01-01 01:00:00,1.223650,0.802317,0.546183,0.459600,1.762017,0.394583,0.447167,0.581833,1.256733,4.089967,...,0.847483,0.737950,6.913767,0.262100,1.083350,0.245883,0.934550,1.374417,0.266783,0.444617
2017-01-01 02:00:00,0.667667,0.459883,0.425467,0.352217,1.170683,0.321000,0.292850,0.575683,1.358817,0.767333,...,0.818467,0.687533,1.616400,0.327267,0.983483,0.245683,0.946933,1.157917,0.274350,0.462567
2017-01-01 03:00:00,0.477950,0.488367,0.445467,0.321100,0.876433,0.305867,0.358683,0.557833,1.298883,0.498483,...,0.838250,0.686200,0.427600,0.670867,1.081733,0.255217,0.979700,1.008100,0.242517,0.302167
2017-01-01 04:00:00,0.414017,0.463400,0.429967,0.425067,1.131033,3.525317,0.510967,0.560133,1.354433,0.489683,...,1.319850,0.729500,0.398100,0.532500,1.008100,0.252750,0.959883,1.048167,0.251650,0.299300

In [4]:
no_components = 15
aggregate_fft = houses_fft.sum(axis=1)

f = np.argsort(abs(aggregate_fft.real))[-no_components:]
f[0] = 52 #add the week frequency, it appears further down the component list (~25)

reduced_houses = houses_fft.loc[f]
reduced_houses = reduced_houses.T #swap columns and rows so the predictors are the columns
reduced_houses.index = reduced_houses.index.astype(int)
N = len(reduced_houses.index)

reduced_houses = reduced_houses.astype(np.float64)

reduced_houses.head()

C:\Users\bfesc\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py:703: ComplexWarning: Casting complex values to real discards the imaginary part
  return arr.astype(dtype)

,52,729,8026,728,35,8719,2,8752,8390,364,1,8753,365,8389,0
26,498.368220,-229.226180,-291.392239,-291.392239,-18.164868,-18.164868,550.789980,550.789980,-1167.495627,-1167.495627,-2586.304946,-2586.304946,2582.959184,2582.959184,11281.015350
59,-57.070036,-571.801729,-247.582863,-247.582863,-278.311053,-278.311053,2488.134469,2488.134469,32.326009,32.326009,333.085037,333.085037,-1717.966541,-1717.966541,14186.745350
86,41.405552,-251.023763,-512.181967,-512.181967,-132.549231,-132.549231,-150.229780,-150.229780,-25.619756,-25.619756,-2741.345873,-2741.345873,-920.650038,-920.650038,13235.825567
93,743.105888,-291.480219,-192.577252,-192.577252,-352.450402,-352.450402,1193.498941,1193.498941,-2900.977837,-2900.977837,-1744.714190,-1744.714190,6363.768252,6363.768252,1899.465467
94,523.313653,258.616656,-228.422177,-228.422177,-63.284254,-63.284254,339.754795,339.754795,-363.422372,-363.422372,-1178.259436,-1178.259436,787.342730,787.342730,6463.021133

In [5]:
response_data = pd.read_csv('C:\\Users\\bfesc\\Documents\\Master_thesis\\master_data\\dataport\\dataport-metadata.csv', 
                header = 0, index_col = 0)

response_data.head()

,active_record,building_type,program_579,program_baseline,program_energy_internet_demo,program_lg_appliance,program_verizon,program_ccet_group,program_civita_group,city,...,refrigerator1,refrigerator2,security1,shed1,sprinkler1,utilityroom1,venthood1,waterheater1,waterheater2,winecooler1
dataid,,,,,,,,,,,,,,,,,,,,,
2836,NaN,Single-Family Home,NaN,NaN,yes,NaN,NaN,NaN,NaN,Austin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2743,NaN,Single-Family Home,NaN,NaN,yes,NaN,NaN,NaN,NaN,Austin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5323,NaN,Single-Family Home,NaN,yes,yes,NaN,NaN,NaN,NaN,Austin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8560,NaN,Single-Family Home,NaN,yes,yes,NaN,NaN,NaN,NaN,Austin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3313,NaN,Single-Family Home,NaN,yes,yes,NaN,NaN,NaN,NaN,Austin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
pv_houses = response_data[response_data['pv'] == 'yes'].index
ev_houses = response_data[response_data['car1'] == 'yes'].index

pv_response = np.zeros(N)
ev_response = np.zeros(N)
for i in range(N):
    if int(reduced_houses.index[i]) in pv_houses:
        pv_response[i] += 1
    if int(reduced_houses.index[i]) in ev_houses:
        ev_response[i] += 1

#reduced_houses['PV'] = pv_responsereduced_houses['EV'] = ev_response

In [7]:
model_lr = LinearRegression()
model_lr.fit(reduced_houses, pv_response)
model_lr.coef_

array([ -3.27764328e-05,   1.54528080e-05,  -1.73731169e+08,
         1.73731169e+08,   9.28200639e+07,  -9.28200639e+07,
        -2.03974197e+08,   2.03974197e+08,  -1.67864402e+09,
         1.67864402e+09,   9.25047504e+09,  -9.25047504e+09,
        -7.93218755e+09,   7.93218755e+09,  -1.83582306e-05])

In [8]:
model_pv_ols = sm.OLS(pv_response,reduced_houses)
fit = model_pv_ols.fit()
fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.849
Model:                            OLS   Adj. R-squared:                  0.843
Method:                 Least Squares   F-statistic:                     128.9
Date:                Sun, 18 Feb 2018   Prob (F-statistic):           1.38e-79
Time:                        16:22:19   Log-Likelihood:                -51.670
No. Observations:                 215   AIC:                             121.3
Df Residuals:                     206   BIC:                             151.7
Df Model:                           9
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
52          6.399e-05   7.56e-05      0.847      0.398    -8.5e-05       0.000
729         1.723e-05   4.44e-05      0.388      0.699   -7.04e-05       0.000
8026          -0.0002   4.42e-05     -3.554      0.000      -0.000   -6.99e-05
728           -0.0002   4.42e-05     -3.554      0.000      -0.000   -6.99e-05
35            -0.0003    6.7e-05     -3.871      0.000      -0.000      -0.000
8719          -0.0003    6.7e-05     -3.871      0.000      -0.000      -0.000
2           2.437e-06    1.8e-05      0.136      0.892    -3.3e-05    3.78e-05
8752        2.437e-06    1.8e-05      0.136      0.892    -3.3e-05    3.78e-05
8390         4.18e-05   2.32e-05      1.801      0.073   -3.97e-06    8.76e-05
364          4.18e-05   2.32e-05      1.801      0.073   -3.97e-06    8.76e-05
1           5.837e-06   9.84e-06      0.593      0.554   -1.36e-05    2.52e-05
8753        5.837e-06   9.84e-06      0.593      0.554   -1.36e-05    2.52e-05
365         7.914e-05   1.16e-05      6.851      0.000    5.64e-05       0.000
8389        7.914e-05   1.16e-05      6.851      0.000    5.64e-05       0.000
0          -1.176e-05   4.66e-06     -2.524      0.012   -2.09e-05   -2.57e-06
==============================================================================
Omnibus:                       37.847   Durbin-Watson:                   2.122
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               83.755
Skew:                           0.821   Prob(JB):                     6.50e-19
Kurtosis:                       5.579   Cond. No.                     3.02e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.8e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [9]:
model_ev_ols = sm.OLS(ev_response,reduced_houses)
fit = model_ev_ols.fit()
fit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.290
Model:                            OLS   Adj. R-squared:                  0.259
Method:                 Least Squares   F-statistic:                     9.334
Date:                Sun, 18 Feb 2018   Prob (F-statistic):           7.35e-12
Time:                        16:22:19   Log-Likelihood:                -95.291
No. Observations:                 215   AIC:                             208.6
Df Residuals:                     206   BIC:                             238.9
Df Model:                           9
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
52            -0.0002   9.26e-05     -1.752      0.081      -0.000    2.03e-05
729         7.145e-05   5.44e-05      1.313      0.191   -3.58e-05       0.000
8026       -3.125e-05   5.41e-05     -0.578      0.564      -0.000    7.54e-05
728        -3.125e-05   5.41e-05     -0.578      0.564      -0.000    7.54e-05
35         -2.919e-05   8.21e-05     -0.355      0.723      -0.000       0.000
8719       -2.919e-05   8.21e-05     -0.355      0.723      -0.000       0.000
2           1.213e-05    2.2e-05      0.552      0.582   -3.12e-05    5.55e-05
8752        1.213e-05    2.2e-05      0.552      0.582   -3.12e-05    5.55e-05
8390        2.634e-05   2.84e-05      0.926      0.355   -2.97e-05    8.24e-05
364         2.634e-05   2.84e-05      0.926      0.355   -2.97e-05    8.24e-05
1           2.694e-05   1.21e-05      2.234      0.027    3.17e-06    5.07e-05
8753        2.694e-05   1.21e-05      2.234      0.027    3.17e-06    5.07e-05
365         3.505e-05   1.42e-05      2.477      0.014    7.15e-06    6.29e-05
8389        3.505e-05   1.42e-05      2.477      0.014    7.15e-06    6.29e-05
0           1.451e-05   5.71e-06      2.543      0.012    3.26e-06    2.58e-05
==============================================================================
Omnibus:                       40.729   Durbin-Watson:                   2.060
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               58.801
Skew:                           1.270   Prob(JB):                     1.70e-13
Kurtosis:                       3.340   Cond. No.                     3.02e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.8e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [10]:
n_folds = 5
fold_size = int(N/n_folds)
folds = np.random.permutation(np.arange(N)).reshape((n_folds,fold_size))
errors = np.zeros(n_folds)

for i in range(n_folds):
    test = folds[i]
    train = np.delete(folds,i,0).flatten()
    pv_tree = tree.DecisionTreeClassifier()
    fit = pv_tree.fit(X=reduced_houses.iloc[train],y=pv_response[train])
    errors[i] = np.sum((pv_tree.predict(reduced_houses.iloc[test]) - pv_response[test])**2)/fold_size # generalization error
    
print("CV generalization error", 1 - errors.sum()/n_folds)

CV generalization error 0.939534883721

In [21]:
import graphviz 
dot_data = tree.export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("iris") 

dot_data = tree.export_graphviz(clf, out_file=None, 
                         feature_names=iris.feature_names,  
                         class_names=iris.target_names,  
                         filled=True, rounded=True,  
                         special_characters=True)  
graph = graphviz.Source(dot_data)  
graph

{'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'presort': False,
 'random_state': None,
 'splitter': 'best'}